"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CloseIcon = exports.EnvelopeIcon = exports.SortIcon = exports.DeleteIcon = exports.TagIcon = exports.FolderIcon = exports.FolderMinusIcon = exports.FilterIcon = exports.SearchIcon = exports.TimesIcon = exports.PlusIcon = exports.CommentIcon = void 0;
var React = require("react");
var FixedWidthIcon_1 = require("./FixedWidthIcon");
exports.CommentIcon = function () { return <FixedWidthIcon_1.FixedWidthIcon name="fas fa-comment-alt"/>; };
exports.PlusIcon = function () { return <FixedWidthIcon_1.FixedWidthIcon name="fas fa-plus"/>; };
exports.TimesIcon = function () { return <FixedWidthIcon_1.FixedWidthIcon name="fas fa-times"/>; };
exports.SearchIcon = function () { return <FixedWidthIcon_1.FixedWidthIcon name="fas fa-search"/>; };
exports.FilterIcon = function () { return <FixedWidthIcon_1.FixedWidthIcon name="fas fa-filter"/>; };
exports.FolderMinusIcon = function () { return <FixedWidthIcon_1.FixedWidthIcon name="fas fa-folder-minus"/>; };
exports.FolderIcon = function () { return <FixedWidthIcon_1.FixedWidthIcon name="fas fa-folder-plus"/>; };
exports.TagIcon = function () { return <FixedWidthIcon_1.FixedWidthIcon name="fas fa-tag"/>; };
exports.DeleteIcon = function () { return <FixedWidthIcon_1.FixedWidthIcon name="fas fa-trash"/>; };
exports.SortIcon = function () { return <FixedWidthIcon_1.FixedWidthIcon name="fal fa-sort-alt"/>; };
exports.EnvelopeIcon = function () { return <FixedWidthIcon_1.FixedWidthIcon name="fas fa-envelope"/>; };
exports.CloseIcon = exports.TimesIcon;
