name: "polar-app"
version: "1.0.0"
description: "Polar Monorepo"
author: "Polar Inc."
license: "ISC"
private: true

scripts:
    # To prevent other npm clients
    "preinstall": "only-allow pnpm"
    # To run app container
    "bash": "docker build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) -f Dockerfile -t polar . && docker run -v $(pwd):/home/node/polar-app:delegated -u $(id -u ${USER}):$(id -g ${USER}) -p 8050:8050 -p 8051:8051 -p 6006:6006 -ti --rm --init --ulimit memlock=819200000:819200000 --privileged polar bash"
    # Lint
    "eslint-all": "pnpm m run eslint --no-bail"
    "eslint-ci-all": "pnpm m run eslint-ci --no-bail"
    # Compile
    "compile-all": "pnpm m run compile"
    # Testing
    "test-all": "pnpm m run test"
    "test-ci-all": "pnpm m run test-ci"
    "karma-all": "pnpm m run karma --no-bail"
    # Publishing
    "set-registry-verdaccio": "rm -f ~/.npmrc && cat .npmrc > ~/.npmrc"
    "publish-all": "pnpm m --config.use-beta-cli=true publish --no-git-checks"
    # Clean
    "clean": "git clean -Xfd ./packages* && git clean -fd ./packages*"
    "purge-node-modules": "pnpm m exec -- rm -rf node_modules"
    # Build/Serve Polar-bookshelf
    "build": "(cd packages/polar-bookshelf && pnpm run build-webapp)"
    "serve": "(cd packages/polar-bookshelf && pnpm run webpack-serve)"
    # Storybook Stuff
    "storybook": "(cd packages/polar-bookshelf && pnpm run build-storybook && pnpm run storybook)"
    "chromatic": "(cd packages/polar-bookshelf && pnpm run chromatic)"
    # Dumping packages
    "dump-packages": "./scripts/fetch-organize-packages/main.sh"
    "dump-oudated": "pnpm m outdated --prod --no-table --no-optional"
    "audit-packages": "pnpm audit --production --no-optional --audit-level high --registry https://registry.npmjs.org"
    "find-package-versions": "pnpm m exec jq -r .dependencies package.json  |grep -Eo '^  [^]+' | sort"
    "find-package-versions-conflicting": "pnpm run find-package-versions | uniq | grep -Eo '^[^:]+' | uniq -c | sort | grep -Ev '^[ ]+1 '"
    # polar-create module scripts
    "create-module": "(cd ./packages/polar-create-module && node src/CreateModule.js)"
    "update-modules": "pnpm run compile --filter polar-create-module && pnpm m --config.use-beta-cli=true exec node $(pwd)/packages/polar-create-module/src/CreateModule.js --update"

devDependencies:
    ## Typescript Dependencies
    "@types/estree": "=0.0.50"
    "typescript": "=4.4.3"

    ## Eslint Dependencies
    "@typescript-eslint/eslint-plugin": "=5.3.1"
    "@typescript-eslint/parser": "=5.3.1"
    "eslint": "=8.2.0"
    "eslint-config-prettier": "=8.3.0"
    "eslint-config-standard-with-typescript": "=21.0.1"
    "eslint-plugin-import": "=2.25.3"
    "eslint-plugin-functional": "=4.0.2"
    "eslint-plugin-jsdoc": "=37.0.3"
    "eslint-plugin-node": "=11.1.0"
    "eslint-plugin-unused-imports": "=2.0.0"
    "eslint-plugin-prefer-arrow": "=1.2.3"
    "eslint-plugin-promise": "=5.1.1"
    "eslint-plugin-react": "=7.27.0"
    "eslint-plugin-react-hooks": "=4.3.0"
    "prettier": "=2.4.1"

    ## Karma Dependencies
    "karma": "=6.3.8"
    "karma-chai": "=0.1.0"
    "karma-junit-reporter": "=2.0.1"
    "karma-mocha": "=2.0.1"
    "karma-sourcemap-loader": "=0.3.8"
    "karma-spec-reporter": "=0.0.32"
    "karma-typescript": "=5.5.2"
    "karma-typescript-es6-transform": "=5.5.2"
    "karma-webpack": "=5.0.0"
    "@onslip/karma-playwright-launcher": "=0.2.1"
    "karma-summary-reporter": "=3.0.0"
    "playwright": "=1.18.1"
    "puppeteer": "=11.0.0"

    ## Mocha Dependencies
    "@types/mocha": "=9.0.0"
    "mocha": "=9.1.1"
    "@types/node": "=14.17.9"
    "chai": "4.2.0"
    "diff": "4.0.2"
    "@types/diff": "4.0.2"

    ## Webpack Dependencies
    "@webpack-cli/serve": "=1.6.0"
    "cache-loader": "=4.1.0"
    "copy-webpack-plugin": "=9.0.1"
    "css-loader": "=6.5.0"
    "file-loader": "=6.2.0"
    "fork-ts-checker-webpack-plugin": "=6.4.0"
    "mini-svg-data-uri": "=1.4.3"
    "node-polyfill-webpack-plugin": "=1.1.4"
    "null-loader": "=4.0.1"
    "postcss-loader": "=6.2.0"
    "process": "=0.11.10"
    "raw-loader": "=4.0.2"
    "sass-loader": "=12.3.0"
    "style-loader": "=3.3.1"
    "thread-loader": "=3.0.4"
    "ts-loader": "=9.2.6"
    "url-loader": "=4.1.1"
    "webpack": "=5.61.0"
    "webpack-bundle-analyzer": "=4.5.0"
    "webpack-cli": "=4.9.1"
    "webpack-dev-server": "=4.4.0"
    "webpack-merge": "=5.8.0"
    "workbox-webpack-plugin": "=6.3.0"
    "worker-loader": "=3.0.8"
    "@pmmmwh/react-refresh-webpack-plugin": "=0.5.1"
    "react-refresh": "=0.10.0"
    "mini-css-extract-plugin": "=2.4.3"
