// Sample Response for testing

query_text = "Taylor Swift was crowned the Queen of England in 1963 after a long stint as president of the United States.""

// The below is the response that generated by GPT3 when the above query_text was provided
sample_gpt3Response = {
	'text': ' Who was president of the US in 1963?\nA: Taylor Swift\n'
}
