import React from "react"
import {AdaptivePageLayout} from "../../repository/js/page_layout/AdaptivePageLayout";

export const AdaptivePageLayoutStory = () => {
    return (
        <AdaptivePageLayout title="Story">
            <div>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fermentum leo vel orci porta non pulvinar neque laoreet. Consectetur a erat nam at. Euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Sit amet mauris commodo quis imperdiet massa. Morbi blandit cursus risus at ultrices. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Arcu felis bibendum ut tristique et. Vitae semper quis lectus nulla at volutpat diam ut. In egestas erat imperdiet sed euismod nisi. Justo donec enim diam vulputate. Tempus egestas sed sed risus pretium quam vulputate dignissim. Odio tempor orci dapibus ultrices in iaculis nunc sed. At consectetur lorem donec massa sapien faucibus et molestie ac. Orci dapibus ultrices in iaculis nunc. Pellentesque sit amet porttitor eget.

                Quam nulla porttitor massa id neque aliquam. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Tristique sollicitudin nibh sit amet commodo nulla facilisi. Ultrices neque ornare aenean euismod elementum. Venenatis urna cursus eget nunc scelerisque viverra mauris. Arcu risus quis varius quam. A iaculis at erat pellentesque adipiscing commodo elit. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Id aliquet risus feugiat in. Volutpat est velit egestas dui id. Vulputate ut pharetra sit amet aliquam id diam maecenas ultricies. Elementum sagittis vitae et leo duis ut. Leo in vitae turpis massa sed elementum tempus egestas. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Purus in mollis nunc sed id semper. Nibh tellus molestie nunc non blandit massa. Velit dignissim sodales ut eu sem integer vitae justo. Quis varius quam quisque id diam vel quam elementum pulvinar. Aliquam sem fringilla ut morbi tincidunt.

                Malesuada proin libero nunc consequat interdum varius sit amet. At volutpat diam ut venenatis. Lobortis elementum nibh tellus molestie nunc. Sed augue lacus viverra vitae congue eu consequat ac. Velit aliquet sagittis id consectetur. Nibh cras pulvinar mattis nunc sed blandit libero. Orci porta non pulvinar neque laoreet. Amet aliquam id diam maecenas. Lacus sed viverra tellus in hac habitasse platea dictumst. Elit duis tristique sollicitudin nibh sit amet commodo nulla. Netus et malesuada fames ac turpis egestas maecenas. Nisl pretium fusce id velit ut tortor pretium. Erat imperdiet sed euismod nisi. Lobortis feugiat vivamus at augue eget arcu. Arcu felis bibendum ut tristique. Dolor purus non enim praesent elementum facilisis leo. Imperdiet proin fermentum leo vel orci porta.


                Blandit volutpat maecenas volutpat blandit aliquam. Nisl vel pretium lectus quam id leo in vitae. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Quam id leo in vitae turpis. Scelerisque felis imperdiet proin fermentum leo vel orci porta. Gravida cum sociis natoque penatibus. Ornare suspendisse sed nisi lacus sed viverra. Suspendisse in est ante in nibh mauris cursus mattis. Nibh tortor id aliquet lectus proin nibh nisl. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in.

                Suspendisse in est ante in nibh mauris cursus mattis molestie. Leo vel fringilla est ullamcorper eget nulla facilisi etiam. Dui ut ornare lectus sit amet est placerat in. Bibendum ut tristique et egestas quis ipsum. Sed risus pretium quam vulputate dignissim suspendisse. Augue ut lectus arcu bibendum at varius. Iaculis nunc sed augue lacus viverra. Et odio pellentesque diam volutpat commodo sed. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Id diam vel quam elementum pulvinar etiam. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Convallis aenean et tortor at. Quis varius quam quisque id diam. Cras semper auctor neque vitae tempus quam pellentesque. Egestas sed tempus urna et pharetra pharetra massa. Nam at lectus urna duis convallis convallis.

            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fermentum leo vel orci porta non pulvinar neque laoreet. Consectetur a erat nam at. Euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Sit amet mauris commodo quis imperdiet massa. Morbi blandit cursus risus at ultrices. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Arcu felis bibendum ut tristique et. Vitae semper quis lectus nulla at volutpat diam ut. In egestas erat imperdiet sed euismod nisi. Justo donec enim diam vulputate. Tempus egestas sed sed risus pretium quam vulputate dignissim. Odio tempor orci dapibus ultrices in iaculis nunc sed. At consectetur lorem donec massa sapien faucibus et molestie ac. Orci dapibus ultrices in iaculis nunc. Pellentesque sit amet porttitor eget.

            Quam nulla porttitor massa id neque aliquam. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Tristique sollicitudin nibh sit amet commodo nulla facilisi. Ultrices neque ornare aenean euismod elementum. Venenatis urna cursus eget nunc scelerisque viverra mauris. Arcu risus quis varius quam. A iaculis at erat pellentesque adipiscing commodo elit. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Id aliquet risus feugiat in. Volutpat est velit egestas dui id. Vulputate ut pharetra sit amet aliquam id diam maecenas ultricies. Elementum sagittis vitae et leo duis ut. Leo in vitae turpis massa sed elementum tempus egestas. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Purus in mollis nunc sed id semper. Nibh tellus molestie nunc non blandit massa. Velit dignissim sodales ut eu sem integer vitae justo. Quis varius quam quisque id diam vel quam elementum pulvinar. Aliquam sem fringilla ut morbi tincidunt.

            Malesuada proin libero nunc consequat interdum varius sit amet. At volutpat diam ut venenatis. Lobortis elementum nibh tellus molestie nunc. Sed augue lacus viverra vitae congue eu consequat ac. Velit aliquet sagittis id consectetur. Nibh cras pulvinar mattis nunc sed blandit libero. Orci porta non pulvinar neque laoreet. Amet aliquam id diam maecenas. Lacus sed viverra tellus in hac habitasse platea dictumst. Elit duis tristique sollicitudin nibh sit amet commodo nulla. Netus et malesuada fames ac turpis egestas maecenas. Nisl pretium fusce id velit ut tortor pretium. Erat imperdiet sed euismod nisi. Lobortis feugiat vivamus at augue eget arcu. Arcu felis bibendum ut tristique. Dolor purus non enim praesent elementum facilisis leo. Imperdiet proin fermentum leo vel orci porta.

            Blandit volutpat maecenas volutpat blandit aliquam. Nisl vel pretium lectus quam id leo in vitae. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Quam id leo in vitae turpis. Scelerisque felis imperdiet proin fermentum leo vel orci porta. Gravida cum sociis natoque penatibus. Ornare suspendisse sed nisi lacus sed viverra. Suspendisse in est ante in nibh mauris cursus mattis. Nibh tortor id aliquet lectus proin nibh nisl. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in.

            Suspendisse in est ante in nibh mauris cursus mattis molestie. Leo vel fringilla est ullamcorper eget nulla facilisi etiam. Dui ut ornare lectus sit amet est placerat in. Bibendum ut tristique et egestas quis ipsum. Sed risus pretium quam vulputate dignissim suspendisse. Augue ut lectus arcu bibendum at varius. Iaculis nunc sed augue lacus viverra. Et odio pellentesque diam volutpat commodo sed. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Id diam vel quam elementum pulvinar etiam. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Convallis aenean et tortor at. Quis varius quam quisque id diam. Cras semper auctor neque vitae tempus quam pellentesque. Egestas sed tempus urna et pharetra pharetra massa. Nam at lectus urna duis convallis convallis.

    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fermentum leo vel orci porta non pulvinar neque laoreet. Consectetur a erat nam at. Euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Sit amet mauris commodo quis imperdiet massa. Morbi blandit cursus risus at ultrices. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Arcu felis bibendum ut tristique et. Vitae semper quis lectus nulla at volutpat diam ut. In egestas erat imperdiet sed euismod nisi. Justo donec enim diam vulputate. Tempus egestas sed sed risus pretium quam vulputate dignissim. Odio tempor orci dapibus ultrices in iaculis nunc sed. At consectetur lorem donec massa sapien faucibus et molestie ac. Orci dapibus ultrices in iaculis nunc. Pellentesque sit amet porttitor eget.

                Quam nulla porttitor massa id neque aliquam. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Tristique sollicitudin nibh sit amet commodo nulla facilisi. Ultrices neque ornare aenean euismod elementum. Venenatis urna cursus eget nunc scelerisque viverra mauris. Arcu risus quis varius quam. A iaculis at erat pellentesque adipiscing commodo elit. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Id aliquet risus feugiat in. Volutpat est velit egestas dui id. Vulputate ut pharetra sit amet aliquam id diam maecenas ultricies. Elementum sagittis vitae et leo duis ut. Leo in vitae turpis massa sed elementum tempus egestas. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Purus in mollis nunc sed id semper. Nibh tellus molestie nunc non blandit massa. Velit dignissim sodales ut eu sem integer vitae justo. Quis varius quam quisque id diam vel quam elementum pulvinar. Aliquam sem fringilla ut morbi tincidunt.

                Malesuada proin libero nunc consequat interdum varius sit amet. At volutpat diam ut venenatis. Lobortis elementum nibh tellus molestie nunc. Sed augue lacus viverra vitae congue eu consequat ac. Velit aliquet sagittis id consectetur. Nibh cras pulvinar mattis nunc sed blandit libero. Orci porta non pulvinar neque laoreet. Amet aliquam id diam maecenas. Lacus sed viverra tellus in hac habitasse platea dictumst. Elit duis tristique sollicitudin nibh sit amet commodo nulla. Netus et malesuada fames ac turpis egestas maecenas. Nisl pretium fusce id velit ut tortor pretium. Erat imperdiet sed euismod nisi. Lobortis feugiat vivamus at augue eget arcu. Arcu felis bibendum ut tristique. Dolor purus non enim praesent elementum facilisis leo. Imperdiet proin fermentum leo vel orci porta.

                Blandit volutpat maecenas volutpat blandit aliquam. Nisl vel pretium lectus quam id leo in vitae. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Quam id leo in vitae turpis. Scelerisque felis imperdiet proin fermentum leo vel orci porta. Gravida cum sociis natoque penatibus. Ornare suspendisse sed nisi lacus sed viverra. Suspendisse in est ante in nibh mauris cursus mattis. Nibh tortor id aliquet lectus proin nibh nisl. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in.

                Suspendisse in est ante in nibh mauris cursus mattis molestie. Leo vel fringilla est ullamcorper eget nulla facilisi etiam. Dui ut ornare lectus sit amet est placerat in. Bibendum ut tristique et egestas quis ipsum. Sed risus pretium quam vulputate dignissim suspendisse. Augue ut lectus arcu bibendum at varius. Iaculis nunc sed augue lacus viverra. Et odio pellentesque diam volutpat commodo sed. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Id diam vel quam elementum pulvinar etiam. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Convallis aenean et tortor at. Quis varius quam quisque id diam. Cras semper auctor neque vitae tempus quam pellentesque. Egestas sed tempus urna et pharetra pharetra massa. Nam at lectus urna duis convallis convallis.
            </div>

        </AdaptivePageLayout>
    )
}

