#!/bin/bash

set -e

commit_repo() {
    dir="${1}"
    version=$(cat lerna.json | jq -r .version) &&
    (cd "${dir}" && commit -m "Commit of version ${version} for release" && git push)
}

npm run-script dist-version &&
commit_repo .
