#!/bin/bash

# we have to have this as an isolated script because npm is insanely broken WRT
# npm repositories and we have to exit npm each time we change credentials.

npm run-script set-registry-bytesafe-rw &&
npm run-script dist-release-webapp-init &&
npm run-script set-registry-default-rw &&
npm run-script dist-release-webapp-release
