#!/bin/bash

set -e

for repo in `cat conf/repos.conf`; do
    name=$(basename ${repo} .git)
    echo ${name}

    git pull --no-edit -s subtree ${name} master

done

# now pull in the main (root)
git pull --no-edit -s subtree polar-app master
