#!/bin/bash

git-import-no-prefix() {

  name=${1}
  repo=${2}

  echo "Adding remote..."

  # TODO: always remove the remote first , then re-add it ...

  git remote add -f ${name} ${repo}
  git fetch ${name}
  git merge -s ours --no-commit --allow-unrelated-histories ${name}/master
  git read-tree -m -u ${name}/master
  git commit -m "Imported ${name} as a subtree."

}

git-import-main() {

  # do the main one now

  git-import-no-prefix polar-app https://github.com/burtonator/polar-app.git

}

git-import-packages() {

  for repo in `cat conf/repos.conf`; do

    echo ${repo}
    name=$(basename ${repo} .git)
    echo ${name}

    ./sbin/git-sync-import ${name} ${repo}

  done

}

git-import-main
git-import-packages

git push
