#!/bin/bash

# TODO:
# - we need a git incoming command
#    https://stackoverflow.com/questions/1331385/how-can-i-see-incoming-commits-in-git
#
#    - THEN we need to make sure if we can pull incoming commits properly and make sure the diff applied is correct


fetchRemoteID() {

    origin="${1}"
    git ls-remote ${origin} HEAD | grep -Eo "^........................................"

}

computeRemotes() {

    for origin in `cat conf/repos.conf`; do
        echo -n "${origin}: "
        fetchRemoteID ${origin}
    done

}

filesIdentical() {

    a="${1}"
    b="${2}"

    cmp ${a} ${b} >/dev/null 2>&1
    return $?
}

doExec() {

    touch .remotes

    # compute the new remotes.
    computeRemotes > /tmp/.remotes

    # https://stackoverflow.com/questions/8139885/shellscript-action-if-two-files-are-different

    if ! filesIdentical /tmp/.remotes .remotes; then
        #./sbin/git-sync-reset && ./sbin/git-sync-init
        echo differ
    else
        echo "No updates to sync"
    fi

    # update the remotes so that it makes it into the commit
    mv /tmp/.remotes .

}

SLEEP_DURATION=60

while true; do
    doExec
    echo "Sleeping for ${SLEEP_DURATION}"
    sleep ${SLEEP_DURATION}
done
