#!/bin/bash

set -e

###
#
# go through the configured repositories and pull them down to initialize them.
mkdir -p packages
for repo_url in `cat conf/repos.conf`; do

    (cd packages && git clone ${repo_url})

done

echo "Telling git to store passwords locally..."
