#!/bin/bash

set -e

get_git_dir_from_url() {

    repo=${1}
    echo "${repo}" | grep -Eo '[a-zA-Z0-9_.-]+.git$' | sed -E 's/\.git//g;'

}

mkdir -p packages

###
#
# go through the configured repositories and pull them down to initialize them.

for repo_url in `cat conf/repos.conf`; do

    dir_name=$(get_git_dir_from_url "${repo_url}")
    dir="packages/${dir_name}"

    if [ ! -d "${dir}" ]; then
        git clone "${repo_url}" "${dir}"
    else
        echo "Skipping ${repo_url} in ${dir}.  Already cloned."
    fi

done

echo "Telling git to store passwords locally..."
