import {DatastoreGetFile} from './impl/groups/DatastoreGetFile';
import {MailinglistFunction} from './impl/MailinglistFunction';
import {StripeWebhookFunction} from './impl/stripe/StripeWebhookFunction';
import {StripeChangePlanFunction} from './impl/stripe/StripeChangePlanFunction';
import {StripeCancelSubscriptionFunction} from './impl/stripe/StripeCancelSubscriptionFunction';
import {GroupProvisionFunction} from './impl/groups/GroupProvisionFunction';
import {GroupJoinFunction} from './impl/groups/GroupJoinFunction';
import {GroupDeleteFunction} from './impl/groups/GroupDeleteFunction';
import {ProfileUpdateFunction} from './impl/groups/ProfileUpdateFunction';
import {GroupDocsAddFunction} from './impl/groups/GroupDocsAddFunction';
import {GroupLeaveFunction} from './impl/groups/GroupLeaveFunction';
import {DocChangeVisibilityFunction} from './impl/groups/DocChangeVisibilityFunction';
import {DatastoreImportFileFunction} from './impl/groups/DatastoreImportFileFunction';
import {ProfileDeleteFunction} from './impl/groups/ProfileDeleteFunction';
import {GroupGetFunction} from './impl/groups/GroupGetFunction';
import {GroupInviteFunction} from './impl/groups/GroupInviteFunction';
import {GroupMemberDeleteFunction} from './impl/groups/GroupMemberDeleteFunctions';
import {GroupDocMetaWriteFunction} from "./impl/groups/GroupDocMetaWriteFunction";
import {Webapp} from "./impl/webapp/Webapp";
import {Sitemap} from "./impl/sitemaps/Sitemap";
import {GroupSitemap} from "./impl/sitemaps/GroupSitemap";
import {DocAddFunction} from "./impl/docs/DocAddFunctions";
import {SearchFunction} from "./impl/search/SearchFunction";

exports.mailinglist = MailinglistFunction;
exports.StripeWebhook = StripeWebhookFunction;
exports.StripeChangePlan = StripeChangePlanFunction;
exports.StripeCancelSubscription = StripeCancelSubscriptionFunction;
exports.datastoreGetFile = DatastoreGetFile;
exports.groupProvision = GroupProvisionFunction;
exports.groupJoin = GroupJoinFunction;
exports.groupDelete = GroupDeleteFunction;
exports.groupDocsAdd = GroupDocsAddFunction;
exports.profileUpdate = ProfileUpdateFunction;
exports.profileDelete = ProfileDeleteFunction;
exports.groupLeave = GroupLeaveFunction;
exports.docChangeVisibility = DocChangeVisibilityFunction;
exports.datastoreImportFile = DatastoreImportFileFunction;
exports.groupGet = GroupGetFunction;
exports.groupInvite = GroupInviteFunction;
exports.groupMemberDelete = GroupMemberDeleteFunction;
exports.GroupDocMetaWriteFunction = GroupDocMetaWriteFunction;
exports.webapp = Webapp;
exports.groupSitemap = GroupSitemap;
exports.sitemap = Sitemap;
exports.docAdd = DocAddFunction;
exports.search = SearchFunction;
