import * as React from 'react';
import {NULL_FUNCTION} from "polar-shared/src/util/Functions";
import {ckeditor5, CKEditor5BalloonEditor} from './ckeditor5/CKEditor5BalloonEditor';
import Button from '@material-ui/core/Button';
import {CKEditor5GlobalCss} from "./ckeditor5/CKEditor5GlobalCss";
import BalloonEditor from "@ckeditor/ckeditor5-build-balloon";

console.log(BalloonEditor.builtinPlugins.map((plugin: any) => plugin.pluginName ));


export const CKEditor5Story2 = () => {

    return (
        <div>
            <CKEditor5GlobalCss/>

            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>
            <CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'
                                    preEscaped={true}
                                    onChange={NULL_FUNCTION}
                                    onEditor={NULL_FUNCTION}/>

                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}
                {/*<CKEditor5BalloonEditor content='this is the content there are many like it but this one is mine.'*/}
                {/*                        preEscaped={true}*/}
                {/*                        onChange={NULL_FUNCTION}*/}
                {/*                        onEditor={NULL_FUNCTION}/>*/}

        </div>
    )
}